import { QuestDef } from './types';

export const MAIN_QUESTS_CATALOG: QuestDef[] = [
  // --- ATO I: O DESPERTAR DO ECO ---
  {
    id: 'main_act1_ch1',
    category: 'main',
    act: 1,
    chapterNumber: 1,
    title: 'O Primeiro Despertar',
    description: 'Você acordou sem memória no Bosque Sussurrante. Derrote a imitação do Vazio e sinta a vida voltar ao seu corpo.',
    npcId: 'alma_mundo',
    npcName: 'Voz da Alma-Mundo',
    unlockedAtStage: 1,
    objectives: [
      {
        id: 'obj_act1_1',
        type: 'kill',
        description: 'Elimine 20 monstros no Bosque ou Floresta Antiga',
        requiredAmount: 20,
        currentAmount: 0,
      },
      {
        id: 'obj_act1_2',
        type: 'level',
        description: 'Alcançar o Nível 5 com seu personagem',
        requiredAmount: 5,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 500,
      forgeFragments: 50,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'A Alma-Mundo sussurra pela primeira vez: você não é um ser comum, mas um Eco que se recusa a ser apagado.',
  },
  {
    id: 'main_act1_ch2',
    category: 'main',
    act: 1,
    chapterNumber: 2,
    title: 'A Marca das Ruínas',
    description: 'Progreva pelas fases da campanha e derrote os guardiões dos biomas primários.',
    npcId: 'archivist_valeria',
    npcName: 'Valéria, a Arquivista Astral',
    unlockedAtStage: 1,
    objectives: [
      {
        id: 'obj_act1_boss1',
        type: 'kill',
        targetId: 'boss_forest_golem',
        description: 'Derrote o Golem de Pedra Silvestre',
        requiredAmount: 1,
        currentAmount: 0,
      },
      {
        id: 'obj_act1_stage',
        type: 'stage',
        description: 'Alcançar a Fase 5 (Ruínas Sombrias)',
        requiredAmount: 5,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 1500,
      forgeFragments: 250,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'Valéria observa seus registros: as Ruínas Sombrias são a prova de que este mundo já caiu e renasceu inúmeras vezes.',
  },
  {
    id: 'main_act1_ch3',
    category: 'main',
    act: 1,
    chapterNumber: 3,
    title: 'Lembrar Para Crescer',
    description: 'Ao encontrar a barreira de força dos monstros, realize a Ascensão para gravar suas cicatrizes na alma.',
    npcId: 'alma_mundo',
    npcName: 'Voz da Alma-Mundo',
    unlockedAtStage: 5,
    objectives: [
      {
        id: 'obj_act1_ascend',
        type: 'ascend',
        description: 'Realize a sua Primeira Ascensão',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 3000,
      forgeFragments: 300,
      storyItemId: 'story_shard_memory',
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'Ascender não é morrer: é absorver o aprendizado de uma vida inteira e retornar mais forte.',
  },

  // --- ATO II: A RECONSTRUÇÃO ASTRAL ---
  {
    id: 'main_act2_ch1',
    category: 'main',
    act: 2,
    chapterNumber: 1,
    title: 'O Domínio da Maestria',
    description: 'Leve sua classe inicial até o limite do aprendizado para abrir os Caminhos Ascendentes.',
    npcId: 'archivist_valeria',
    npcName: 'Valéria, a Arquivista Astral',
    unlockedAtStage: 6,
    objectives: [
      {
        id: 'obj_act2_stage',
        type: 'stage',
        description: 'Alcançar a Fase 10 (Pesadelo)',
        requiredAmount: 10,
        currentAmount: 0,
      },
      {
        id: 'obj_act2_lvl50',
        type: 'level',
        description: 'Alcançar o Nível 50 com seu herói',
        requiredAmount: 50,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 5000,
      forgeFragments: 500,
      studyInsignias: 50,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Eco da sua classe desabrocha. Os caminhos de Paladino, Clérigo e Ladrão agora se alinham à sua jornada.',
  },
  {
    id: 'main_act2_ch2',
    category: 'main',
    act: 2,
    chapterNumber: 2,
    title: 'Erguendo a Cidadela',
    description: 'Reconstrua as alas da Cidadela Astral para ter uma base de operações contra o Vazio.',
    npcId: 'forge_master_vulkan',
    npcName: 'Vulkan, Mestre da Forja',
    unlockedAtStage: 10,
    objectives: [
      {
        id: 'obj_act2_build',
        type: 'citadel_build',
        description: 'Aprimore qualquer construção na Cidadela Astral',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 10000,
      forgeFragments: 800,
      studyInsignias: 100,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'Vulkan martela a bigorna encandescente: a Cidadela ganha forma na mesma medida em que sua vontade se fortalece.',
  },
  {
    id: 'main_act2_ch3',
    category: 'main',
    act: 2,
    chapterNumber: 3,
    title: 'A Forja e o Metal',
    description: 'Supere o tier Apocalipse e forje um equipamento digno dos conquistadores ancestrais.',
    npcId: 'forge_master_vulkan',
    npcName: 'Vulkan, Mestre da Forja',
    unlockedAtStage: 15,
    objectives: [
      {
        id: 'obj_act2_craft',
        type: 'forge',
        description: 'Refine ou forje um equipamento de raridade Lendária ou superior',
        requiredAmount: 1,
        currentAmount: 0,
      },
      {
        id: 'obj_act2_boss',
        type: 'kill',
        targetId: 'boss_archdemon',
        description: 'Derrote o Arquidemônio das Ruínas',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 25000,
      forgeFragments: 1500,
      storyItemId: 'story_seal_archdemon',
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'Com o Selo do Arquidemônio em mãos, as 20 fases da campanha conhecida se rendem ao seu poder.',
  },

  // --- ATO III: O CÁRCERE DOS CACOS ---
  {
    id: 'main_act3_ch1',
    category: 'main',
    act: 3,
    chapterNumber: 1,
    title: 'A Entropia do Purgatório',
    description: 'Adentre o Purgatório — a região espelhada onde os fragmentos da Alma-Mundo são mantidos em cárcere.',
    npcId: 'void_wanderer',
    npcName: 'O Andarilho do Vazio',
    unlockedAtStage: 21,
    objectives: [
      {
        id: 'obj_act3_stage',
        type: 'stage',
        description: 'Alcançar a Fase 25 no Purgatório',
        requiredAmount: 25,
        currentAmount: 0,
      },
      {
        id: 'obj_act3_kill',
        type: 'kill',
        targetId: 'purgatory_specter',
        description: 'Elimine 30 Espectros do Purgatório',
        requiredAmount: 30,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 50000,
      forgeFragments: 2500,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Andarilho do Vazio observa: o Purgatório não foi feito para proteger os vivos dos monstros, mas para conter a própria Alma.',
  },
  {
    id: 'main_act3_ch2',
    category: 'main',
    act: 3,
    chapterNumber: 2,
    title: 'A Tranca de Pedra',
    description: 'Derrote o Guardião dos Cacos na Fase 30 e liberte os limites da campanha.',
    npcId: 'archivist_valeria',
    npcName: 'Valéria, a Arquivista Astral',
    unlockedAtStage: 25,
    objectives: [
      {
        id: 'obj_act3_boss',
        type: 'kill',
        targetId: 'boss_crystal_guardian',
        description: 'Derrote o Guardião dos Cacos (Fase 30)',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 100000,
      forgeFragments: 5000,
      storyItemId: 'story_astral_compass',
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Guardião dos Cacos desmorona em cristais. A barreira da Fase 30 foi estilhaçada!',
  },
  {
    id: 'main_act3_ch3',
    category: 'main',
    act: 3,
    chapterNumber: 3,
    title: 'Os Ecos do Vazio',
    description: 'Com a barreira da Fase 30 destruída, criaturas de elite do Purgatório começam a vazar para as fases anteriores. Reforce a vigilância da Cidadela e extermine essas anomalias.',
    npcId: 'void_wanderer',
    npcName: 'O Andarilho do Vazio',
    unlockedAtStage: 30,
    objectives: [
      {
        id: 'obj_act3_elite',
        type: 'kill_elite',
        description: 'Elimine 15 Elites do Purgatório',
        requiredAmount: 15,
        currentAmount: 0,
      },
      {
        id: 'obj_act3_watch',
        type: 'citadel_build',
        targetId: 'watchTower',
        description: 'Aprimore a Torre de Vigia Astral',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 75000,
      forgeFragments: 3500,
      studyInsignias: 75,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Andarilho do Vazio observa a nova Torre de Vigia se erguer: "Agora vocês veem o que eu sempre vi — o Vazio nunca parou de vazar, vocês é que escolheram não olhar."',
  },

  // --- ATO IV: A PROMESSA QUEBRADA ---
  {
    id: 'main_act4_ch1',
    category: 'main',
    act: 4,
    chapterNumber: 1,
    title: 'O Despertar do Pandemônio',
    description: 'Desbloqueie o Modo Pandemônio no Altar de Alma e encare a infinitude do Vazio.',
    npcId: 'void_wanderer',
    npcName: 'O Andarilho do Vazio',
    unlockedAtStage: 30,
    objectives: [
      {
        id: 'obj_act4_stage',
        type: 'stage',
        description: 'Alcançar a Fase 35 no Modo Pandemônio',
        requiredAmount: 35,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 250000,
      forgeFragments: 10000,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Pandemônio aprende a cada rodada. O combate agora é um ciclo sem fim de aperfeiçoamento.',
  },
  {
    id: 'main_act4_ch2',
    category: 'main',
    act: 4,
    chapterNumber: 2,
    title: 'A Fome do Vazio',
    description: 'O Modo Pandemônio consome tudo o que toca. Sacie a Cidadela com a energia que sobra do caos, antes que ela vire fome sobre vocês.',
    npcId: 'void_wanderer',
    npcName: 'O Andarilho do Vazio',
    unlockedAtStage: 35,
    objectives: [
      {
        id: 'obj_act4_elite',
        type: 'kill_elite',
        description: 'Elimine 25 Elites no Modo Pandemônio',
        requiredAmount: 25,
        currentAmount: 0,
      },
      {
        id: 'obj_act4_siphon',
        type: 'citadel_build',
        targetId: 'forgeWorkshop',
        description: 'Aprimore a Oficina da Forja',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 400000,
      forgeFragments: 15000,
      studyInsignias: 150,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: '"Você alimenta a Cidadela com o que o Vazio rejeitou", diz o Andarilho. "Isso é mais poesia do que ele gostaria de admitir."',
  },
  {
    id: 'main_act4_ch3',
    category: 'main',
    act: 4,
    chapterNumber: 3,
    title: 'A Última Promessa',
    description: 'Avance ainda mais fundo no Modo Pandemônio e recupere o fragmento que o Vazio jurou nunca devolver.',
    npcId: 'void_wanderer',
    npcName: 'O Andarilho do Vazio',
    unlockedAtStage: 40,
    objectives: [
      {
        id: 'obj_act4_stage45',
        type: 'stage',
        description: 'Alcançar a Fase 45 no Modo Pandemônio',
        requiredAmount: 45,
        currentAmount: 0,
      },
      {
        id: 'obj_act4_elite2',
        type: 'kill_elite',
        description: 'Elimine 40 Elites no Modo Pandemônio',
        requiredAmount: 40,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 700000,
      forgeFragments: 25000,
      storyItemId: 'story_void_promise',
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Vazio cede um fragmento de si mesmo — uma promessa que jurou e não cumpriu, agora em suas mãos. "Guarde-a", sussurra o Andarilho. "Promessas quebradas ainda pesam."',
  },

  // --- ATO V: O ESPELHO DA ALMA ---
  {
    id: 'main_act5_ch1',
    category: 'main',
    act: 5,
    chapterNumber: 1,
    title: 'Além da Roda',
    description: 'Conclua o Rito de Transcendência e explore a Ecoterra para sentir o reflexo divino.',
    npcId: 'avatar_echo',
    npcName: 'O Eco do Avatar',
    unlockedAtStage: 50,
    objectives: [
      {
        id: 'obj_act5_transcend',
        type: 'transcend',
        description: 'Conclua a sua primeira Transcendência',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 1000000,
      transcendenceEssence: 20,
      storyItemId: 'story_vessel_avatar',
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'A roda do destino foi quebrada. Sua alma não mais se apaga na Ascensão — ela transcende.',
  },
  {
    id: 'main_act5_ch2',
    category: 'main',
    act: 5,
    chapterNumber: 2,
    title: 'O Peso do Infinito',
    description: 'A Transcendência não é um destino, é um ciclo. Prove que você pode enfrentá-lo novamente, já mudado pelo que aprendeu da primeira vez.',
    npcId: 'avatar_echo',
    npcName: 'O Eco do Avatar',
    unlockedAtStage: 50,
    objectives: [
      {
        id: 'obj_act5_transcend2',
        type: 'transcend',
        description: 'Conclua a sua 2ª Transcendência',
        requiredAmount: 2,
        currentAmount: 0,
      },
      {
        id: 'obj_act5_altar',
        type: 'citadel_build',
        targetId: 'synchronyAltar',
        description: 'Aprimore o Altar de Sincronia Elemental',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 1500000,
      transcendenceEssence: 40,
      studyInsignias: 200,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: '"Você voltou", diz o Eco do Avatar. "A maioria só faz isso uma vez e chama de destino. Duas vezes é escolha."',
  },
  {
    id: 'main_act5_ch3',
    category: 'main',
    act: 5,
    chapterNumber: 3,
    title: 'O Avatar Desperto',
    description: 'Nos limites entre o que você era e o que se tornou, uma nova forma espera para ser reivindicada.',
    npcId: 'avatar_echo',
    npcName: 'O Eco do Avatar',
    unlockedAtStage: 50,
    objectives: [
      {
        id: 'obj_act5_transcend3',
        type: 'transcend',
        description: 'Conclua a sua 3ª Transcendência',
        requiredAmount: 3,
        currentAmount: 0,
      },
      {
        id: 'obj_act5_craft',
        type: 'forge',
        description: 'Forje ou refine 3 equipamentos de raridade Lendária ou superior',
        requiredAmount: 3,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 2500000,
      transcendenceEssence: 75,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O reflexo no Espelho da Alma finalmente sorri de volta. Você não é mais um Eco tentando sobreviver — é um Avatar decidindo o que vem a seguir.',
  },

  // --- ATO VI: A NOTA DOS CÉUS ---
  {
    id: 'main_act6_ch1',
    category: 'main',
    act: 6,
    chapterNumber: 1,
    title: 'O Chamado das Profundezas',
    description: 'Mergulhe nas Profundezas do Abismo e resgate os Ecos Afogados da cidadela submersa.',
    npcId: 'sunken_castellan',
    npcName: 'O Castelão Afundado',
    unlockedAtStage: 50,
    objectives: [
      {
        id: 'obj_act6_echoes',
        type: 'abyss_echo',
        description: 'Resgate 5 Ecos Afogados nas Profundezas',
        requiredAmount: 5,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 300000,
      abyssPearls: 500,
      storyItemId: 'story_drowned_locket',
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'Os Ecos Afogados cantam em uníssono no Salão. A cidadela afundada volta a respirar.',
  },
  {
    id: 'main_act6_ch2',
    category: 'main',
    act: 6,
    chapterNumber: 2,
    title: 'A Resposta dos Céus',
    description: 'Enfrente O Leviatã do Ciclo no Trono Afundado e escute a nota que atravessou as nuvens.',
    npcId: 'sky_herald',
    npcName: 'O Heraldo dos Céus',
    unlockedAtStage: 60,
    objectives: [
      {
        id: 'obj_act6_leviathan',
        type: 'kill',
        targetId: 'boss_leviathan',
        description: 'Derrote O Leviatã do Ciclo no Trono Afundado',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 800000,
      transcendenceEssence: 50,
      storyItemId: 'story_herald_horn',
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Caco Submerso cantou uma única nota... e uma presença gloriosa além das nuvens respondeu!',
  },
  {
    id: 'main_act6_ch3',
    category: 'main',
    act: 6,
    chapterNumber: 3,
    title: 'O Coração do Abismo',
    description: 'Com o Leviatã silenciado, reivindique o poder que ele guardou por mil anos e feche o ciclo do Trono Afundado.',
    npcId: 'sunken_castellan',
    npcName: 'O Castelão Afundado',
    unlockedAtStage: 70,
    objectives: [
      {
        id: 'obj_act6_echoes2',
        type: 'abyss_echo',
        description: 'Resgate 15 Ecos Afogados nas Profundezas',
        requiredAmount: 15,
        currentAmount: 0,
      },
      {
        id: 'obj_act6_runeword',
        type: 'runeword',
        targetId: 'coracao_leviata',
        description: 'Grave a Palavra Rúnica Coração do Leviatã',
        requiredAmount: 1,
        currentAmount: 0,
      },
    ],
    rewards: {
      gold: 1200000,
      abyssPearls: 1000,
      transcendenceEssence: 100,
    },
    isCompleted: false,
    isClaimed: false,
    completionLore: 'O Coração do Leviatã pulsa em suas mãos agora. O Trono Afundado, pela primeira vez em mil anos, tem um guardião que escolheu ficar — não por juramento, mas por vontade.',
  },
];
