import { TransitionPayload } from '../store/useTransitionStore';

export const BIOME_TRANSITIONS: Record<number, TransitionPayload> = {
  1: {
    id: 'biome_1_forest',
    type: 'biome',
    title: 'Bosque Sussurrante',
    subtitle: 'Novo Bioma Alcançado (Fases 1–5)',
    loreText: 'O vento entre as árvores antigas sussurra avisos de velhas lendas. As criaturas da mata observam a cada passo de sua jornada.',
    speakerId: 'alma_mundo',
    speakerName: 'Alma do Mundo',
    factionColor: '#10b981',
    icon: '🌲',
  },
  6: {
    id: 'biome_6_desert',
    type: 'biome',
    title: 'Deserto de Baator',
    subtitle: 'Novo Bioma Alcançado (Fases 6–10)',
    loreText: 'As areias causticantes queimam sob o sol escaldante. Ruínas esquecidas revelam a presença de antigas bestas no meio das dunas.',
    speakerId: 'archivist_valeria',
    speakerName: 'Arquivista Valéria',
    factionColor: '#f59e0b',
    icon: '⏳',
  },
  11: {
    id: 'biome_11_crystal',
    type: 'biome',
    title: 'Caverna de Cristal',
    subtitle: 'Novo Bioma Alcançado (Fases 11–15)',
    loreText: 'Cristais cintilantes refletem a luz da mística magia abissal. O ar ressoa com vibrações de poder elemental indisciplinado.',
    speakerId: 'void_wanderer',
    speakerName: 'Caminhante do Vazio',
    factionColor: '#38bdf8',
    icon: '💎',
  },
  16: {
    id: 'biome_16_volcano',
    type: 'biome',
    title: 'Vulcão Primordial',
    subtitle: 'Novo Bioma Alcançado (Fases 16–20)',
    loreText: 'Rios de lava cortam o chão de pedra escura. O calor sufocante e a fúria das chamas desafiam até os campeões mais experientes.',
    speakerId: 'forge_master_vulkan',
    speakerName: 'Mestre da Forja Vulkan',
    factionColor: '#f97316',
    icon: '🌋',
  },
  21: {
    id: 'biome_21_citadel',
    type: 'biome',
    title: 'Cidadela Abandonada',
    subtitle: 'Novo Bioma Alcançado (Fases 21–25)',
    loreText: 'Grandes salões de pedra desmoronada ecoam o passado de uma civilização caída. Sombras perambulam por seus corredores esquecidos.',
    speakerId: 'sunken_castellan',
    speakerName: 'Castelão do Abismo',
    factionColor: '#a855f7',
    icon: '🏛️',
  },
};

export const DIFFICULTY_TRANSITIONS: Record<string, TransitionPayload> = {
  nightmare: {
    id: 'diff_nightmare',
    type: 'difficulty',
    title: 'Dificuldade: Pesadelo',
    subtitle: 'Aumento de Desafio',
    loreText: 'O véu da noite se adensa. Inimigos ganham atributos aprimorados e maior agressividade, mas recompensas muito mais raras aguardam!',
    speakerId: 'avatar_echo',
    speakerName: 'Eco do Avatar',
    factionColor: '#ec4899',
    icon: '🌙',
  },
  hell: {
    id: 'diff_hell',
    type: 'difficulty',
    title: 'Dificuldade: Inferno',
    subtitle: 'Desafio Máximo',
    loreText: 'As chamas da perdição engolfam a arena de combate. Apenas aqueles equipados com forja lendária e habilidades perfeitas sobreviverão.',
    speakerId: 'forge_master_vulkan',
    speakerName: 'Mestre Vulkan',
    factionColor: '#ef4444',
    icon: '🔥',
  },
};

export const TOWER_TRANSITIONS: Record<number, TransitionPayload> = {
  10: {
    id: 'tower_floor_10',
    type: 'tower',
    title: 'Torre de Provações — Andar 10',
    subtitle: 'Marco de Ascensão',
    loreText: 'Você superou os primeiros desafios da torre. A pressão mística aumenta e as primeiras bênçãos e maldições começam a se manifestar!',
    speakerId: 'sky_herald',
    speakerName: 'Arauto Celestial',
    factionColor: '#fbbf24',
    icon: '🏰',
  },
  25: {
    id: 'tower_floor_25',
    type: 'tower',
    title: 'Torre de Provações — Andar 25',
    subtitle: 'Marco Avançado',
    loreText: 'Os andares intermediários exigem maestria técnica e preparo estratégico. O topo ainda está longe, mas sua determinação é inabalável.',
    speakerId: 'sky_herald',
    speakerName: 'Arauto Celestial',
    factionColor: '#38bdf8',
    icon: '⚡',
  },
  50: {
    id: 'tower_floor_50',
    type: 'tower',
    title: 'Torre de Provações — Andar 50',
    subtitle: 'Metade do Caminho',
    loreText: 'Meio século de andares sob seus pés. Poucos mortais tocaram esta altura e viveram para contar as histórias.',
    speakerId: 'alma_mundo',
    speakerName: 'Alma do Mundo',
    factionColor: '#a855f7',
    icon: '🌟',
  },
};

export const ABYSS_BOSS_TRANSITIONS: Record<string, TransitionPayload> = {
  guardian_25: {
    id: 'abyss_guardian_25',
    type: 'abyss',
    title: 'Guardião dos Coralinos Defumados',
    subtitle: 'Vitória no Abismo (Profundidade 25)',
    loreText: 'O primeiro grande guardião do abismo sucumbiu perante o seu avanço. As águas profundas começam a se abrir perante você.',
    speakerId: 'sunken_castellan',
    speakerName: 'Castelão das Profundezas',
    factionColor: '#06b6d4',
    icon: '🌊',
  },
  leviathan: {
    id: 'abyss_leviathan',
    type: 'abyss',
    title: 'O Leviatã Despertado',
    subtitle: 'Confronto Supremo',
    loreText: 'O leviatã das profundezas ruge nas trevas oceânicas. Cada fase de seu combate testará o limite de sua força e vitalidade!',
    speakerId: 'void_wanderer',
    speakerName: 'Caminhante do Vazio',
    factionColor: '#10b981',
    icon: '🐙',
  },
};
